package spring.model;
// Generated 05-jun-2018 15:59:11 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empleados generated by hbm2java
 */
@Entity
@Table(name = "empleados", catalog = "agenda")
public class Empleados implements java.io.Serializable {

	private Integer idempleados;
	private String codEmpleado;
	private String salario;
	private Date fechaAlta;
	private int departamentosIddepartamento;
	private int categoriasIdcategorias;

	public Empleados() {
	}

	public Empleados(String codEmpleado, int departamentosIddepartamento, int categoriasIdcategorias) {
		this.codEmpleado = codEmpleado;
		this.departamentosIddepartamento = departamentosIddepartamento;
		this.categoriasIdcategorias = categoriasIdcategorias;
	}

	public Empleados(String codEmpleado, String salario, Date fechaAlta, int departamentosIddepartamento,
			int categoriasIdcategorias) {
		this.codEmpleado = codEmpleado;
		this.salario = salario;
		this.fechaAlta = fechaAlta;
		this.departamentosIddepartamento = departamentosIddepartamento;
		this.categoriasIdcategorias = categoriasIdcategorias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idempleados", unique = true, nullable = false)
	public Integer getIdempleados() {
		return this.idempleados;
	}

	public void setIdempleados(Integer idempleados) {
		this.idempleados = idempleados;
	}

	@Column(name = "codEmpleado", nullable = false, length = 45)
	public String getCodEmpleado() {
		return this.codEmpleado;
	}

	public void setCodEmpleado(String codEmpleado) {
		this.codEmpleado = codEmpleado;
	}

	@Column(name = "salario", length = 45)
	public String getSalario() {
		return this.salario;
	}

	public void setSalario(String salario) {
		this.salario = salario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaAlta", length = 10)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "departamentos_iddepartamento", nullable = false)
	public int getDepartamentosIddepartamento() {
		return this.departamentosIddepartamento;
	}

	public void setDepartamentosIddepartamento(int departamentosIddepartamento) {
		this.departamentosIddepartamento = departamentosIddepartamento;
	}

	@Column(name = "categorias_idcategorias", nullable = false)
	public int getCategoriasIdcategorias() {
		return this.categoriasIdcategorias;
	}

	public void setCategoriasIdcategorias(int categoriasIdcategorias) {
		this.categoriasIdcategorias = categoriasIdcategorias;
	}

}
