package spring.model;
// Generated 05-jun-2018 15:59:11 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personas generated by hbm2java
 */
@Entity
@Table(name = "personas", catalog = "agenda")
public class Personas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idpersonas;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String dni;
	private Date fechaNacimiento;
	private int empleadosIdempleados;
	private int telefonosIdtelefonos;
	private int direccionesIddirecciones;

	public Personas() {
	}

	public Personas(String nombre, String apellido1, int empleadosIdempleados, int telefonosIdtelefonos,
			int direccionesIddirecciones) {
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.empleadosIdempleados = empleadosIdempleados;
		this.telefonosIdtelefonos = telefonosIdtelefonos;
		this.direccionesIddirecciones = direccionesIddirecciones;
	}

	public Personas(String nombre, String apellido1, String apellido2, String dni, Date fechaNacimiento,
			int empleadosIdempleados, int telefonosIdtelefonos, int direccionesIddirecciones) {
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.dni = dni;
		this.fechaNacimiento = fechaNacimiento;
		this.empleadosIdempleados = empleadosIdempleados;
		this.telefonosIdtelefonos = telefonosIdtelefonos;
		this.direccionesIddirecciones = direccionesIddirecciones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpersonas", unique = true, nullable = false)
	public Integer getIdpersonas() {
		return this.idpersonas;
	}

	public void setIdpersonas(Integer idpersonas) {
		this.idpersonas = idpersonas;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido1", nullable = false, length = 45)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 45)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "dni", length = 20)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaNacimiento", length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "empleados_idempleados", nullable = false)
	public int getEmpleadosIdempleados() {
		return this.empleadosIdempleados;
	}

	public void setEmpleadosIdempleados(int empleadosIdempleados) {
		this.empleadosIdempleados = empleadosIdempleados;
	}

	@Column(name = "telefonos_idtelefonos", nullable = false)
	public int getTelefonosIdtelefonos() {
		return this.telefonosIdtelefonos;
	}

	public void setTelefonosIdtelefonos(int telefonosIdtelefonos) {
		this.telefonosIdtelefonos = telefonosIdtelefonos;
	}

	@Column(name = "direcciones_iddirecciones", nullable = false)
	public int getDireccionesIddirecciones() {
		return this.direccionesIddirecciones;
	}

	public void setDireccionesIddirecciones(int direccionesIddirecciones) {
		this.direccionesIddirecciones = direccionesIddirecciones;
	}

}
