/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M15
 * Generated at: 2018-06-05 10:22:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/admin/Documents/GitHub/ProyectoAgenda/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PorFinAgenda/WEB-INF/lib/spring-webmvc-4.3.8.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1492518452000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1528101413731L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/Documents/GitHub/ProyectoAgenda/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PorFinAgenda/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.8.RELEASE.jar", Long.valueOf(1527586729688L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/Documents/GitHub/ProyectoAgenda/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PorFinAgenda/WEB-INF/lib/spring-webmvc-4.3.8.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1492518452000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"author\" content=\"Colorlib\">\r\n");
      out.write("    <meta name=\"description\" content=\"#\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"#\">\r\n");
      out.write("    <!-- Page Title -->\r\n");
      out.write("    <title>Agenda RoneaWork</title>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500,700,900\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Simple line Icon -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/simple-line-icons.css\">\r\n");
      out.write("    <!-- Themify Icon -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/themify-icons.css\">\r\n");
      out.write("    <!-- Hover Effects -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/set1.css\">\r\n");
      out.write("    <!-- Main CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!--============================= HEADER =============================-->\r\n");
      out.write("    <div class=\"nav-menu\">\r\n");
      out.write("        <div class=\"bg transition\">\r\n");
      out.write("            <div class=\"container-fluid fixed\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("                            <a class=\"navbar-brand\" href=\"index.html\">RoneaWork</a>\r\n");
      out.write("                            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNavDropdown\" aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"icon-menu\"></span>\r\n");
      out.write("              </button>\r\n");
      out.write("                            <div class=\"collapse navbar-collapse justify-content-end\" id=\"navbarNavDropdown\">\r\n");
      out.write("                                <ul class=\"navbar-nav\">\r\n");
      out.write("                                   \r\n");
      out.write("                                    <li class=\"nav-item active\">\r\n");
      out.write("                                        <a class=\"nav-link\" href=\"mostrar\"><strong>Empleados</strong></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"nav-item active\">\r\n");
      out.write("                                        <a class=\"nav-link\" href=\"#\"><strong>CategorÃ­a</strong></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"nav-item active\">\r\n");
      out.write("                                        <a class=\"nav-link\" href=\"#\"><strong>Departamentos</strong></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"nav-item active\">\r\n");
      out.write("                                        <a class=\"nav-link\" href=\"#\"><strong>Personas</strong></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- SLIDER -->\r\n");
      out.write("    <section class=\"slider d-flex align-items-center\">\r\n");
      out.write("        <!-- <img src=\"images/slider.jpg\" class=\"img-fluid\" alt=\"#\"> -->\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"slider-title_box\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-12\">\r\n");
      out.write("                                <div class=\"slider-content_wrap\">\r\n");
      out.write("                                    <h1>Agenda empresarial</h1>\r\n");
      out.write("                                    <h5>Bienvenido a tu agenda personal empresarial, todo lo que necesitas saber a tu alcance con un solo click</h5>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("                            <div class=\"col-md-10\">\r\n");
      out.write("                                <form class=\"form-wrap mt-4\">\r\n");
      out.write("                                    <div class=\"btn-group\" role=\"group\" aria-label=\"Basic example\">\r\n");
      out.write("                                        <input type=\"text\" placeholder=\"Primer Apellido\" class=\"btn-group1\">\r\n");
      out.write("                                        <input type=\"text\" placeholder=\"Segundo apellido\" class=\"btn-group2\">\r\n");
      out.write("                                        <button type=\"submit\" class=\"btn-form\"><span class=\"icon-magnifier search-icon\"></span>SEARCH<i class=\"pe-7s-angle-right\"></i></button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                                <div class=\"slider-link\">\r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--// SLIDER -->\r\n");
      out.write("    <!--//END HEADER -->\r\n");
      out.write("    <!--============================= FIND PLACES =============================-->\r\n");
      out.write("   \r\n");
      out.write("    <!--//END FIND PLACES -->\r\n");
      out.write("    <!--============================= FEATURED PLACES =============================-->\r\n");
      out.write("   \r\n");
      out.write("    <!--//END FEATURED PLACES -->\r\n");
      out.write("    <!--============================= CATEGORIES =============================-->\r\n");
      out.write("\r\n");
      out.write("    <!--//END ADD LISTING -->\r\n");
      out.write("    <!--============================= FOOTER =============================-->\r\n");
      out.write("    <footer class=\"main-block dark-bg\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"copyright\">\r\n");
      out.write("                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                        <p>Copyright &copy; 2018 RoneaWork. All rights reserved </p>\r\n");
      out.write("                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\"><span class=\"ti-facebook\"></span></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><span class=\"ti-twitter-alt\"></span></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><span class=\"ti-instagram\"></span></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!--//END FOOTER -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery, Bootstrap JS. -->\r\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("    <script src=\"js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        $(window).scroll(function() {\r\n");
      out.write("            // 100 = The point you would like to fade the nav in.\r\n");
      out.write("\r\n");
      out.write("            if ($(window).scrollTop() > 100) {\r\n");
      out.write("\r\n");
      out.write("                $('.fixed').addClass('is-sticky');\r\n");
      out.write("\r\n");
      out.write("            } else {\r\n");
      out.write("\r\n");
      out.write("                $('.fixed').removeClass('is-sticky');\r\n");
      out.write("\r\n");
      out.write("            };\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
